<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU0xP3tk\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU0xP3tk/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerU0xP3tk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerU0xP3tk\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerU0xP3tk\srcApp_KernelProdContainer([
    'container.build_hash' => 'U0xP3tk',
    'container.build_id' => '7c667322',
    'container.build_time' => 1644505135,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU0xP3tk');
