<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'inscription' => [[], ['_controller' => 'App\\Controller\\InscriptionController::index'], [], [['text', '/inscription']], [], []],
    'Login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/Login']], [], []],
    'message' => [[], ['_controller' => 'App\\Controller\\messageController::new'], [], [['text', '/message']], [], []],
    'property.new' => [[], ['_controller' => 'App\\Controller\\propertyController::new'], [], [['text', '/biens/form']], [], []],
    'property.index' => [[], ['_controller' => 'App\\Controller\\propertyController::index'], [], [['text', '/biens']], [], []],
    'Home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
];
