# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.contents_dir: '...'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    #configuring a service manually to read services from other repos like in vendor
    cebe\markdown\Markdown: ~

    #configuration manuelle d'un service
    App\Service\Message:
        arguments:
            $contentsDir: '%app.contents_dir%'

    App\Controller\propertyController:
        arguments: ['@doctrine.orm.default_entity_manager']

    App\Command\CreatePropertyCommand:
        tags: ['console.command']

    #les evenements pour les changements liés à l'entité property
    #postUpdate est un evenement qui déclanche avant la mise à jour de l'entité property
    App\EventListener\PropertyChangedNotifier:
        tags:
            - # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'App\Entity\Property'







