<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5LTlnO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5LTlnO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW5LTlnO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW5LTlnO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerW5LTlnO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'W5LTlnO',
    'container.build_id' => '17bea44e',
    'container.build_time' => 1644857114,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5LTlnO');
