<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGKbYZsL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGKbYZsL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGKbYZsL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGKbYZsL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGKbYZsL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GKbYZsL',
    'container.build_id' => '4a59fce5',
    'container.build_time' => 1644855280,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGKbYZsL');
