<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0LJvdip\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0LJvdip/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0LJvdip.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0LJvdip\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0LJvdip\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0LJvdip',
    'container.build_id' => '15e53724',
    'container.build_time' => 1644932992,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0LJvdip');
