<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'AdminPropGere' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminPropertyController::index'], [], [['text', '/admin']], [], []],
    'AdminPropGereID' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminPropertyController::editer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin']], [], []],
    'deleted' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminPropertyController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/DeleteElement']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::Login'], [], [['text', '/login']], [], []],
    'message' => [[], ['_controller' => 'App\\Controller\\messageController::new'], [], [['text', '/message']], [], []],
    'property.show' => [['slug', 'id'], ['_controller' => 'App\\Controller\\propertyController::show'], ['slug' => '[a-z0-9\\-]*'], [['variable', '-', '[^/]++', 'id'], ['variable', '/', '[a-z0-9\\-]*', 'slug'], ['text', '/detailspropery']], [], []],
    'property.index' => [[], ['_controller' => 'App\\Controller\\propertyController::index'], [], [['text', '/biens']], [], []],
    'CreateNewProperty' => [[], ['_controller' => 'App\\Controller\\propertyController::createNewProperty'], [], [['text', '/createNewProperty']], [], []],
    'Home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'logout' => [[], [], [], [['text', '/logout']], [], []],
];
